# Generated by Django 4.1.7 on 2023-02-18 14:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False, verbose_name='نام انگلیسی بیمه')),
                ('name', models.CharField(max_length=100, verbose_name='نام بیمه')),
                ('cover', models.ImageField(blank=True, upload_to='covers/', verbose_name='تصویر بیمه')),
                ('franchising', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='فرانشیز (درصد)')),
                ('bank_account', models.CharField(max_length=100, verbose_name='بانک معرفی شده به بیمه')),
                ('bank_card_num', models.BigIntegerField(blank=True, null=True, verbose_name='شماره حساب')),
                ('branchs_name', models.CharField(max_length=100, verbose_name='نام شعبه')),
                ('total_debits_and_credits', models.BigIntegerField(blank=True, null=True, verbose_name='مجموع بدهکاری و بستانکاری')),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('tariff', models.SlugField(max_length=100, primary_key=True, serialize=False, verbose_name='نام تعرفه به انگلیسی')),
                ('kidney_crusher_cost', models.BigIntegerField(blank=True, null=True, verbose_name='حق العمل سنگ شکنی')),
                ('anesthetic_cost', models.BigIntegerField(blank=True, null=True, verbose_name='حق العمل بیهوشی')),
                ('drug_and_consumables_cost', models.BigIntegerField(blank=True, null=True, verbose_name='هزینه دارو و لوازم مصرفی')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=200, verbose_name='نام خانوادگی')),
                ('father_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام پدر')),
                ('sex', models.CharField(blank=True, choices=[('M', 'مرد'), ('F', 'زن')], max_length=1, null=True, verbose_name='جنسیت')),
                ('birth_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('national_code', models.BigIntegerField(blank=True, null=True, verbose_name='کد ملی')),
                ('phone_number', models.BigIntegerField(blank=True, null=True, verbose_name='تلفن همراه')),
                ('home_phone', models.BigIntegerField(blank=True, null=True, verbose_name='تلفن ثابت')),
                ('date_of_admission', django_jalali.db.models.jDateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ پذیزش')),
                ('file_number', models.CharField(blank=True, max_length=300, null=True, verbose_name='شماره پرونده')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس منزل')),
                ('docter_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام پزشک معرف')),
                ('anesthesia_doctor_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام پزشک بیهوشی')),
                ('presenter', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام معرف')),
                ('operator', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام اپراتور سنگ شکنی')),
                ('supplementary_insurance', models.CharField(blank=True, max_length=100, null=True, verbose_name='بیمه تکمیلی')),
                ('date_of_hospitalization', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بستری')),
                ('date_of_discharge', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ترخیص')),
                ('type_of_surgery', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع عمل')),
                ('payments_status', models.BooleanField(blank=True, default=False, null=True, verbose_name='وضعیت پرداخت')),
                ('delivery_date', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('basic_insurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='skeleton.insurance')),
                ('payment_tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='skeleton.tariff')),
            ],
            options={
                'ordering': ['-date_of_admission'],
            },
        ),
    ]
