# Generated by Django 4.1.7 on 2023-02-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='payments_status',
        ),
        migrations.AddField(
            model_name='patient',
            name='paid',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='وضعیت پرداخت'),
        ),
    ]
