# Generated by Django 2.2.12 on 2023-01-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='docter_name',
            new_name='doctor_name',
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
