# Generated by Django 2.2.12 on 2023-01-20 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0002_auto_20230120_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='doctor_name',
            new_name='docter_name',
        ),
    ]
