# Generated by Django 2.2.12 on 2023-01-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0002_alter_patient_id'),
        ('skeleton', '0003_auto_20230120_1810'),
    ]

    operations = [
    ]
