# Generated by Django 2.2.12 on 2023-02-04 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0004_merge_20230122_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-date_of_admission']},
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateTimeField(verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_admission',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پذیزش'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='docter_name',
            field=models.CharField(max_length=100, verbose_name='نام پزشک'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='father_name',
            field=models.CharField(max_length=100, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='file_number',
            field=models.CharField(max_length=300, verbose_name='شماره پرونده'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='home_phone',
            field=models.BigIntegerField(verbose_name='تلفن ثابت'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_code',
            field=models.BigIntegerField(verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.BigIntegerField(verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], max_length=1, verbose_name='جنسیت'),
        ),
    ]
