# Generated by Django 4.1.7 on 2023-02-18 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0003_patient_payments_status'),
    ]

    operations = [
    ]
