# Generated by Django 4.1.7 on 2023-02-18 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0004_remove_patient_payments_status'),
        ('skeleton', '0005_merge_20230218_2358'),
    ]

    operations = [
    ]
