# Generated by Django 2.2.12 on 2023-02-10 18:51

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0006_auto_20230210_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='salary',
            field=models.CharField(blank=True, default='', max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='دستمزد'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='basic_insurance',
            field=models.CharField(blank=True, choices=[('IRAN', 'بیمه ایران'), ('DANA', 'بیمه دانا'), ('ASIA', 'بیمه آسیا'), ('SOS', 'بیمه SOS'), ('ALBORZ', 'بیمه البرز'), ('SINA', 'بیمه سینا'), ('SEPAH_BANK', 'بیمه بانک سپه'), ('TEJARAT_BANK', 'بیمه بانک تجارت'), ('KESHAVARZI_BANK', 'بیمه بانک کشاورزی'), ('MELLAT', 'بیمه ملت'), ('MA', 'بیمه ما'), ('SAMAN', 'بیمه سامان'), ('SARMAD', 'بیمه سرمد'), ('TEJARATE NO', 'بیمه تجارت نو'), ('ARMAN', 'بیمه آرمان'), ('TAAVON', 'بیمه تعاون'), ('NOVIN', 'بیمه نوین'), ('SAR DAFTARAN', 'بیمه سر دفتران'), ('KAR AFARIN', 'بیمه کارآفرین'), ('SEDA VA SIMA', 'بیمه صدا و سیما'), ('ATIEH SAZAN', 'بیمه آتیه سازان'), ('SHAHRDARI', 'بیمه شهرداری'), ('15 KHORDAD', 'بیمه ۱۵ خرداد')], max_length=50, verbose_name='بیمه پایه'),
        ),
    ]
