# Generated by Django 4.1.7 on 2023-02-18 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0006_merge_20230219_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='paid',
        ),
    ]
