# Generated by Django 2.2.12 on 2023-02-11 01:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0007_auto_20230210_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس منزل'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='anesthesia_doctor_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام پزشک بیهوشی'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='basic_insurance',
            field=models.CharField(blank=True, choices=[('IRAN', 'بیمه ایران'), ('DANA', 'بیمه دانا'), ('ASIA', 'بیمه آسیا'), ('SOS', 'بیمه SOS'), ('ALBORZ', 'بیمه البرز'), ('SINA', 'بیمه سینا'), ('SEPAH_BANK', 'بیمه بانک سپه'), ('TEJARAT_BANK', 'بیمه بانک تجارت'), ('KESHAVARZI_BANK', 'بیمه بانک کشاورزی'), ('MELLAT', 'بیمه ملت'), ('MA', 'بیمه ما'), ('SAMAN', 'بیمه سامان'), ('SARMAD', 'بیمه سرمد'), ('TEJARATE NO', 'بیمه تجارت نو'), ('ARMAN', 'بیمه آرمان'), ('TAAVON', 'بیمه تعاون'), ('NOVIN', 'بیمه نوین'), ('SAR DAFTARAN', 'بیمه سر دفتران'), ('KAR AFARIN', 'بیمه کارآفرین'), ('SEDA VA SIMA', 'بیمه صدا و سیما'), ('ATIEH SAZAN', 'بیمه آتیه سازان'), ('SHAHRDARI', 'بیمه شهرداری'), ('15 KHORDAD', 'بیمه ۱۵ خرداد')], max_length=50, null=True, verbose_name='بیمه پایه'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_admission',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ پذیزش'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='docter_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام پزشک معرف'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='file_number',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='شماره پرونده'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='home_phone',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='تلفن ثابت'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_code',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='operator',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام اپراتور سنگ شکنی'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='presenter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام معرف'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'مرد'), ('F', 'زن')], max_length=1, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='supplementary_insurance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='بیمه تکمیلی'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='type_of_surgery',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع عمل'),
        ),
    ]
