# Generated by Django 2.2.12 on 2023-02-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0008_auto_20230211_0445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('name', models.CharField(max_length=100, verbose_name='نام بیمه')),
                ('franchising', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='فرانشیز (درصد)')),
                ('bank_account', models.CharField(max_length=100, verbose_name='بانک معرفی شده به بیمه')),
                ('bank_card_num', models.BigIntegerField(blank=True, null=True, verbose_name='شماره حساب')),
                ('branchs_name', models.CharField(max_length=100, verbose_name='نام شعبه')),
                ('total_debits_and_credits', models.BigIntegerField(blank=True, null=True, verbose_name='مجموع بدهکاری و بستانکاری')),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='basic_insurance',
        ),
    ]
