# Generated by Django 4.1.7 on 2023-02-21 21:20

from django.db import migrations, models
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0008_patient_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='موارد')),
                ('price', models.BigIntegerField(blank=True, null=True, verbose_name='قیمت')),
                ('date', django_jalali.db.models.jDateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ خرید')),
                ('name', models.CharField(max_length=100, verbose_name='نام خریدار')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='patient',
            name='delivery_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تحویل'),
        ),
    ]
