# Generated by Django 2.2.12 on 2023-02-11 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0009_auto_20230211_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='basic_insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skeleton.Insurance'),
        ),
    ]
