# Generated by Django 4.1.7 on 2023-02-24 05:59

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0009_fund_alter_patient_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='delivery_date',
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_admission',
            field=django_jalali.db.models.jDateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ پذیزش'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_discharge',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ ترخیص'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_hospitalization',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ بستری'),
        ),
    ]
