# Generated by Django 2.2.12 on 2023-02-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0010_patient_basic_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='franchising',
            field=models.DecimalField(decimal_places=2, max_digits=2, verbose_name='فرانشیز (درصد)'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='slug',
            field=models.SlugField(max_length=100, primary_key=True, serialize=False, verbose_name='نام انگلیسی بیمه'),
        ),
    ]
