# Generated by Django 4.1.7 on 2023-02-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0010_remove_patient_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, default='-', null=True, verbose_name='آدرس منزل'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='anesthesia_doctor_name',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='نام پزشک بیهوشی'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='description',
            field=models.TextField(blank=True, default='توضیحاتی وارد نشده است', null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='docter_name',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='نام پزشک معرف'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='father_name',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='file_number',
            field=models.CharField(blank=True, default='-', max_length=300, null=True, verbose_name='شماره پرونده'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='home_phone',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='تلفن ثابت'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_code',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='operator',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='نام اپراتور سنگ شکنی'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='presenter',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='نام معرف'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='supplementary_insurance',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='بیمه تکمیلی'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='type_of_surgery',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='نوع عمل'),
        ),
    ]
