# Generated by Django 4.1.7 on 2023-02-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0011_alter_patient_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='title',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='description',
            field=models.TextField(blank=True, default='موردی وارد نشده است.', null=True, verbose_name='موارد'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='name',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='نام خریدار'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='price',
            field=models.BigIntegerField(blank=True, default='مبلغ وارد نشده است', null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='bank_account',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='بانک معرفی شده به بیمه'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='branchs_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام شعبه'),
        ),
    ]
