# Generated by Django 2.2.12 on 2023-02-15 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0011_auto_20230211_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('tariff', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='نام انگلیسی بیمه')),
                ('kidney_crusher_cost', models.BigIntegerField(blank=True, null=True, verbose_name='کد ملی')),
                ('anesthetic_cost', models.BigIntegerField(blank=True, null=True, verbose_name='کد ملی')),
                ('drug_and_consumables_cost', models.BigIntegerField(blank=True, null=True, verbose_name='کد ملی')),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='salary',
        ),
        migrations.AddField(
            model_name='patient',
            name='payment_tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skeleton.Tariff'),
        ),
    ]
