# Generated by Django 4.1.7 on 2023-02-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0012_fund_title_alter_fund_description_alter_fund_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='bank_account',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='بانک معرفی شده به بیمه'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='bank_card_num',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='شماره حساب'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='branchs_name',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='نام شعبه'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='total_debits_and_credits',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='مجموع بدهکاری و بستانکاری'),
        ),
    ]
