# Generated by Django 2.2.12 on 2023-02-16 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0013_auto_20230216_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='payment_status',
            field=models.CharField(choices=[('P', 'پزداخت شده'), ('U', 'پزداخت نشده')], default='U', max_length=1, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='basic_insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='skeleton.Insurance'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='payment_tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='skeleton.Tariff'),
        ),
    ]
