# Generated by Django 4.1.7 on 2023-02-17 15:05

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0013_auto_20230216_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_admission',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ پذیزش'),
        ),
    ]
