# Generated by Django 4.1.7 on 2023-03-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0013_alter_insurance_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='boss_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='نام مدیرعامل مرکز'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='موارد'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='نام خریدار'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='price',
            field=models.BigIntegerField(blank=True, default='', null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='bank_account',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='بانک معرفی شده به بیمه'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='bank_card_num',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='شماره حساب'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='branchs_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='نام شعبه'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='total_debits_and_credits',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='مجموع بدهکاری و بستانکاری'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, default='', null=True, verbose_name='آدرس منزل'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='anesthesia_doctor_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='نام پزشک بیهوشی'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='docter_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='نام پزشک معرف'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='file_number',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='شماره پرونده'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='home_phone',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='تلفن ثابت'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_code',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='operator',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='نام اپراتور سنگ شکنی'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='presenter',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='نام معرف'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='supplementary_insurance',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='بیمه تکمیلی'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='type_of_surgery',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='نوع عمل'),
        ),
    ]
