# Generated by Django 4.1.7 on 2023-03-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0014_insurance_boss_name_alter_fund_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='franchising',
        ),
        migrations.AddField(
            model_name='patient',
            name='franchising',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='فرانشیز (درصد)'),
        ),
    ]
