# Generated by Django 4.1.7 on 2023-02-16 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0015_bar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bar',
        ),
    ]
