# Generated by Django 4.1.7 on 2023-03-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0015_remove_insurance_franchising_patient_franchising'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='discount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='تخفیف'),
        ),
    ]
