# Generated by Django 4.1.7 on 2023-03-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0016_patient_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='discount',
            field=models.BigIntegerField(default=0, verbose_name='تخفیف'),
        ),
    ]
