# Generated by Django 4.1.7 on 2023-02-17 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0014_alter_patient_date_of_admission'),
        ('skeleton', '0017_patient_delivery_date'),
    ]

    operations = [
    ]
