# Generated by Django 4.1.7 on 2023-03-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0017_alter_patient_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='canceling',
            field=models.BooleanField(default=False, verbose_name='وضعیت پذیرش'),
        ),
    ]
