# Generated by Django 4.1.7 on 2023-02-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0018_merge_20230217_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/', verbose_name='تصویر بیمه'),
        ),
    ]
