# Generated by Django 4.1.7 on 2023-03-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0018_patient_canceling'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='anesthesiologist',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='نام متخصص بیهوشی'),
        ),
    ]
