# Generated by Django 4.1.7 on 2023-04-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0022_epayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='bed',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='هزینه تخت'),
        ),
    ]
