# Generated by Django 4.1.7 on 2023-05-25 06:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0025_alter_patient_franchising'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='franchising',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='فرانشیز (درصد)'),
        ),
    ]
