# Generated by Django 4.1.7 on 2023-05-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0027_alter_patient_franchising'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='franchising',
            field=models.IntegerField(default=0, verbose_name='فرانشیز (درصد)'),
        ),
    ]
