# Generated by Django 4.1.7 on 2023-06-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0029_alter_patient_franchising'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='boss_position',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='سمت'),
        ),
    ]
